### PR TITLE
fix_recursive_mergelists_stack_smash

### PR DESCRIPTION
**Pull request by juj**
Avoids a recursive algorithm for merging use lists, which blows up the call stack and crashes LLVM parsing large .bc files on Windows.

Need to land this immediately/directly to fastcomp, since several partners are blocked on this right now. @sunfishcode , would you like to rally this upstream?

### CODE REVIEW

**Comment by kripken** [comment]
Hopefully @sunfishcode can review this too.

@juj, do you know why this is a problem only on windows?

**Comment by juj** [comment]
It was a difference in thread stack sizes. Actually, in the opencv.js test
case, @sunfishcode was able to crash the stack on his Linux as well, so
guess that windows just has a smaller default stack sizes.

**Comment by kripken** [comment]
thanks, got it.

meanwhile lgtm, except please add an `XXX EMSCRIPTEN` so this is very noticeable in the source as a hack we need to remove.

 (but let's wait on @sunfishcode before merging)

**Comment by juj** [comment]
Sure, added a `XXX EMSCRIPTEN` comment.

**Comment by kripken** [comment]
Well, since so many people are having this issue, let's merge this in for now. We can adjust things later.

**Pull request merged**
