### PR TITLE
Fix 64-bit C++11 atomics when targeting wasm in non-multithreaded mode

### PR DESCRIPTION
**Pull request by juj**

### CODE REVIEW

**Comment by kripken** [comment]
Another option is to let LLVM lower them - that would also avoid calling a function for them. On line 4508 there is
```
  if (!OnlyWebAssembly) {
    // if only wasm, then we can emit i64s, otherwise they must be lowered
    PM.add(createExpandI64Pass());
  } else if (!EnablePthreads) {
    PM.add(createLowerAtomicPass());
  }
```
I think that `else if` is suspect. We need to do that also if `!OnlyWebAssembly`. So this bug should go away if we remove the `else`, I think.

**Comment by juj** [comment]
Hmm, that sounds like a good idea, but trying that out, `createLowerAtomicPass()` doesn't quite seem to be able to lower all atomics, but I see the call handlers still get called on the 64-bit LLVM intrinsics. I suppose we could do both here?

**Comment by juj** [comment]
Tested `python tests/runner.py binaryen*`, `python tests/runner.py`, `python tests/runner.py browser.test_pthread*` and `python tests/runner.py other` to pass.

**Comment by kripken** [comment]
Yeah, should be no harm in doing both. Odd LLVM can't remove all atomics in that pass.

lgtm

**Pull request merged**
