### PR TITLE
VS2013 fix for getRelocData.

### PR DESCRIPTION
**Pull request by juj**
Work around Visual Studio bug https://connect.microsoft.com/VisualStudio/feedback/details/1085387 .

### CODE REVIEW

**Comment by juj** [comment]
This fixes #60. While it's also possible to fix this in other ways, I thought to make the workaround as explicit as possible.

**Comment by kripken** [comment]
@jfbastien - pnacl probably would benefit from this too.

**Comment by jfbastien** [comment]
@juj: would making this non-`static` fix the issue? It's redundant in an anonymous namespace.

**Comment by jfbastien** [comment]
I discussed this with clb on IRC, here's a different fix:
  https://codereview.chromium.org/828553007

**Pull request merged**
