### PR TITLE
Replace ministring with std::string in emcc build of Relooper.cpp

### PR DESCRIPTION
**Pull request by regular**
fixes broken build due to missing ministring.h

### CODE REVIEW

**Comment by kripken** [comment]
Thanks!

**Comment by regular** [comment]
Thank you too!
In case you are interested: [this](http://regular.github.io/fastcomp.js/demo.html) is what I use the emcc build of fastcomp for. (the layout might look familiar to you :) )
And [here](http://github.com/regular/make-llvm-bitcode-for-javascript) is the script that automates all of the BitCode generation. (I can get rid of that `curl` line now ...)

**Comment by kripken** [comment]
Nice!

One note, when I wrote some bad LLVM IR and tried to compile it, it replaced the IR with the error message, so the IR was lost, which surprised me.

**Comment by regular** [comment]
Uh, that's not intentionally, just a side-effect of not having proper error handling yet. I look into it. 
I plan to have three areas: source assembler/optimized assembler/js
Thanks for the feedback! regular/fastcomp.js#5

**Pull request merged**
