### PR TITLE
Fix vs2013 build

### PR DESCRIPTION
**Pull request by juj**
Fixes Visual Studio 2013 incompatibilities that we got from upstream.

CC @jfbastien .

### CODE REVIEW

**Comment by jfbastien** [comment]
Thanks for pointing this out :-)

**Comment by gouletr** [comment]
Great! We can close https://github.com/kripken/emscripten/issues/3738 when this is merged.

**Comment by kripken** [comment]
@jfbastien , do these look good? If you don't have a quick answer, then @juj lgtm but with `XXX EMSCRIPTEN` comments.

In other words lgtm either way, but with comments if these are things pnacl isn't sure they're going to do.

**Comment by jfbastien** [comment]
lgtm, I asked kschimpf to apply the same patch here:
https://codereview.chromium.org/1306183006/

**Comment by kripken** [comment]
Great, thanks.

**Pull request merged**
