### PR TITLE
Allow multiple arities per EM_ASM block, fixes kripken/emscripten#3804.

### PR DESCRIPTION
**Pull request by jjrv**
PR for kripken/emscripten#3804.
Make a set of different arities in template expansions of each `EM_ASM` block.
They need to be ordered to take a shortcut in `emscripten.py` so there's a new typedef `OrderedIntSet` in case `IntSet` is later changed to `std::unordered_set`.

### CODE REVIEW

**Comment by kripken** [comment]
Looks perfect, just needs to wait on the parallel https://github.com/kripken/emscripten/pull/3806 to land together.

**Comment by jjrv** [comment]
A small change in the other PR lifted the ordered set requirement here, so I renamed that variable and removed a now unused one.

**Comment by jjrv** [comment]
Maybe the structure of `asmConstArities` and the code emitting it is now complicated enough to benefit from a clarifying comment.

**Comment by kripken** [comment]
Merged, thanks!

Meanwhile I was thinking that the data structures could be simpler here if we just outputted the max for each id, and a list of all the arities seen overall. However, there seems little downside to providing the full information as this pull does, perhaps we will need it later.

**Pull request merged**
