### PR TITLE
LLVM 4.0

### PR DESCRIPTION
**Pull request by kripken**
This builds upon @dylanmckay's excellent work in merging in LLVM 4.0. I added a few fixes for the test suite. At this point everything seems to pass, so I think this is ready for merge (as usual, with tagging before and after), except for

 * Review. Speaking of which, is there a good git way to see just the "non-merged" changes? I.e., not all the LLVM commits we merged in, but merge conflict resolutions etc.?
 * Would be good if someone does testing on their projects, if not, can happen on incoming
 * Need to verify the merged LLVM commit is exactly the one Rust needs. @brson?

Will open parallel emscripten and clang PRs in a second.

### CODE REVIEW

**Comment by dschuff** [comment]
LGTM!
on a somewhat related note, when was the last time we updated libc++ (to get the new library goodness to go along with this new compiler goodness)?

**Comment by dschuff** [comment]
oh, wrt review. There's not a really good way to review just what we care about; i.e. changes to our diff from upstream. There is a thing called interdiff, which is for viewing diffs-of-diffs, which is sometimes useful. Also you can look directly at a diff if you limit it just to files which are not upstream (which covers a lot of things for fastcomp). `git diff` will accept a list of files on the command line to do this. It seems like I recall having a script to gather that for PNaCl, let me try to find it.

**Comment by kripken** [comment]
Ok, thanks. I reviewed the best diffs I could get. Everything seems to be in order.

Looks like we are just waiting on rust, to know the precise changeset to merge in: https://github.com/rust-lang/rust/issues/37609#issuecomment-276467894 Otherwise we are all ready here.

About libc++, last update we did is `Date:   Mon May 9 23:39:55 2016 +0200` based on the changelog (f8e0b7dc838dea8b713944b5c9469be837826999 in emscripten).

**Comment by kripken** [comment]
Rust still isn't quite ready here, but meanwhile it would be good to merge this and the adjoining PRs, since the clang upgrade fixes some issues that projects have hit.

Any concerns with merging these in?

**Comment by dschuff** [comment]
LGTM!

**Pull request merged**
